    name: Deploy MultiK8s
    on:
      push:
        branches:
          - master
     
    env:
      SHA: $(git rev-parse HEAD)
     
    jobs:
      build:
        runs-on: ubuntu-latest
        permissions:
          contents: "read"
          id-token: "write"
        steps:
          - uses: actions/checkout@v3
     
          - name: Test
            run: |-
              docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              docker build -t magnomos/react-test -f ./client/Dockerfile.dev ./client
              docker run -e CI=true magnomos/react-test npm test
     
          - name: Set Identity Provider
            uses: "google-github-actions/auth@v2"
            with:
              workload_identity_provider: "projects/699344562788/locations/global/workloadIdentityPools/github/attribute.repository/wang-tu-94/multi-k8s"
     
          - name: Set Project
            uses: google-github-actions/setup-gcloud@v2
            with:
              project_id: project-aa1da5a2-0e77-42e9-adf
     
          - name: Auth
            run: |-
              gcloud --quiet auth configure-docker
     
          - name: Get Credentials
            uses: google-github-actions/get-gke-credentials@v2
            with:
              cluster_name: multi-k8s
              location: eu-west9
              project_id: project-aa1da5a2-0e77-42e9-adf
     
          - name: Build
            run: |-
              docker build -t magnomos/multi-client:latest -t magnomos/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
              docker build -t magnomos/multi-server:latest -t magnomos/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
              docker build -t magnomos/multi-worker:latest -t magnomos/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
     
          - name: Push
            run: |-
              docker push magnomos/multi-client:latest
              docker push magnomos/multi-server:latest
              docker push magnomos/multi-worker:latest
     
              docker push magnomos/multi-client:${{ env.SHA }}
              docker push magnomos/multi-server:${{ env.SHA }}
              docker push magnomos/multi-worker:${{ env.SHA }}
     
          - name: Apply
            run: |-
              kubectl apply -f k8s
              kubectl set image deployments/server-deployment server=magnomos/multi-server:${{ env.SHA }}
              kubectl set image deployments/client-deployment client=magnomos/multi-client:${{ env.SHA }}
              kubectl set image deployments/worker-deployment worker=magnomos/multi-worker:${{ env.SHA }}